package com.company.entity;
// Generated Dec 31, 2018 4:23:12 PM by Hibernate Tools 4.3.1



/**
 * Ticker generated by hbm2java
 */
public class Ticker  implements java.io.Serializable {


     private long id;
     private long channelId;
     private int bid;
     private int bidSize;
     private int ask;
     private int askSize;
     private int dailyChange;
     private int dailyChangePerc;
     private int lastPrice;
     private int volume;
     private int high;
     private int low;

    public Ticker() {
    }

    public Ticker(long id, long channelId, int bid, int bidSize, int ask, int askSize, int dailyChange, int dailyChangePerc, int lastPrice, int volume, int high, int low) {
       this.id = id;
       this.channelId = channelId;
       this.bid = bid;
       this.bidSize = bidSize;
       this.ask = ask;
       this.askSize = askSize;
       this.dailyChange = dailyChange;
       this.dailyChangePerc = dailyChangePerc;
       this.lastPrice = lastPrice;
       this.volume = volume;
       this.high = high;
       this.low = low;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getChannelId() {
        return this.channelId;
    }
    
    public void setChannelId(long channelId) {
        this.channelId = channelId;
    }
    public int getBid() {
        return this.bid;
    }
    
    public void setBid(int bid) {
        this.bid = bid;
    }
    public int getBidSize() {
        return this.bidSize;
    }
    
    public void setBidSize(int bidSize) {
        this.bidSize = bidSize;
    }
    public int getAsk() {
        return this.ask;
    }
    
    public void setAsk(int ask) {
        this.ask = ask;
    }
    public int getAskSize() {
        return this.askSize;
    }
    
    public void setAskSize(int askSize) {
        this.askSize = askSize;
    }
    public int getDailyChange() {
        return this.dailyChange;
    }
    
    public void setDailyChange(int dailyChange) {
        this.dailyChange = dailyChange;
    }
    public int getDailyChangePerc() {
        return this.dailyChangePerc;
    }
    
    public void setDailyChangePerc(int dailyChangePerc) {
        this.dailyChangePerc = dailyChangePerc;
    }
    public int getLastPrice() {
        return this.lastPrice;
    }
    
    public void setLastPrice(int lastPrice) {
        this.lastPrice = lastPrice;
    }
    public int getVolume() {
        return this.volume;
    }
    
    public void setVolume(int volume) {
        this.volume = volume;
    }
    public int getHigh() {
        return this.high;
    }
    
    public void setHigh(int high) {
        this.high = high;
    }
    public int getLow() {
        return this.low;
    }
    
    public void setLow(int low) {
        this.low = low;
    }




}


