package com.company.entity;
// Generated Dec 31, 2018 4:23:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long userId;
     private String firstName;
     private String lastName;
     private Date registration;

    public Users() {
    }

	
    public Users(long userId, Date registration) {
        this.userId = userId;
        this.registration = registration;
    }
    public Users(long userId, String firstName, String lastName, Date registration) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.registration = registration;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(Date registration) {
        this.registration = registration;
    }




}


