spring:
  datasource:
    url: jdbc:h2:mem:app
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

cross.origin: http://localhost:4200

springdoc.version: 1:0
